runtime: nodejs14  # Select the Node.js version you need:

# Application configuration: 
instance_class: F2  # You can adjust the instance class according to your needs.

# Definition of handlers for the routes:
handlers:
- url: /.*  # Any path Application configuration:
  script: auto  # Use the default configuration for Node.js.

# Additional configuration if necessary:

env_variables:
  KEY: VALUE  
